In [1]:
import numpy as np

##### 1D - array with size

In [7]:
a=np.array([2,4,6],dtype='int16')
print(a)

[2 4 6]


##### 2D - array

In [4]:
b=np.array([[2,4,6],[1,3,5]])
print(b)

[[2 4 6]
 [1 3 5]]


In [8]:
#get type
a.dtype

dtype('int16')

In [11]:
r=np.array([[2,4,6,8,10],[1,3,5,7,9]])
print(r)

[[ 2  4  6  8 10]
 [ 1  3  5  7  9]]


##### finding positions

In [14]:
r[1,:]

array([1, 3, 5, 7, 9])

In [15]:
r[:,3]

array([8, 7])

In [16]:
r.shape

(2, 5)

In [19]:
r[0,4]

10

In [20]:
print(r)

[[ 2  4  6  8 10]
 [ 1  3  5  7  9]]


In [21]:
r[:,:]

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [22]:
r[1,0:4:2]

array([1, 5])

In [23]:
r[0,4]=14

In [24]:
r[:,:]

array([[ 2,  4,  6,  8, 14],
       [ 1,  3,  5,  7,  9]])

##### Making a matrix with 1 and 0

In [30]:
n=np.ones((5,5))
print(n)

a=np.zeros((3,3))
a[1,1]=9
print(a)

n[1:4,1:4]=a
print(n)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [31]:
a=np.array([2,4,6,8])
print(a)

[2 4 6 8]


##### Mathematics operations

In [32]:
a *2

array([ 4,  8, 12, 16])

In [33]:
a/2

array([1., 2., 3., 4.])

In [34]:
r=np.array([[2,4,6,8,10],[1,3,5,7,9]])
print(r)

[[ 2  4  6  8 10]
 [ 1  3  5  7  9]]


In [35]:
np.full_like(r,4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

##### repeation and trigo

In [36]:
arr=np.array([2,4,6,8])
a=np.repeat(arr,4,axis=0)
print(a)

[2 2 2 2 4 4 4 4 6 6 6 6 8 8 8 8]


In [37]:
np.sin(a)

array([ 0.90929743,  0.90929743,  0.90929743,  0.90929743, -0.7568025 ,
       -0.7568025 , -0.7568025 , -0.7568025 , -0.2794155 , -0.2794155 ,
       -0.2794155 , -0.2794155 ,  0.98935825,  0.98935825,  0.98935825,
        0.98935825])

In [39]:
np.cos(a)

array([-0.41614684, -0.41614684, -0.41614684, -0.41614684, -0.65364362,
       -0.65364362, -0.65364362, -0.65364362,  0.96017029,  0.96017029,
        0.96017029,  0.96017029, -0.14550003, -0.14550003, -0.14550003,
       -0.14550003])

In [40]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
np.min(stats)

1

In [43]:
np.min(stats,axis=0)
np.min(stats,axis=1)

array([1, 4])

##### Reshaping of matrix

In [45]:
before=np.array([[1,2,3],[4,5,6]])
print(before)

after=before.reshape((3,2))
print(after)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


##### Vertical stacking

In [47]:
v1=np.array([1,2,3])
v2=np.array([4,5,6])

np.stack([v1,v2,v1])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

##### Horizontal stacking

In [48]:
h1=np.ones((2,4))
h2=np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [50]:
#index with a list 
a=np.array([2,4,6,8,10,12])
a[[2,3,5]]

array([ 6,  8, 12])